name: kicksafe
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.12.1
  camera: ^0.10.5+9
  image: ^4.1.7
  shared_preferences: ^2.3.2
  firebase_core: ^2.27.0

flutter:
  assets:
    - lib/assets/model/model_unquant.tflite
    - lib/assets/model/labels.txt