// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNaxUbZetx_kFfWr6atp3fbKFfVIBwNhs',
    appId: '1:369737957258:web:088e4d5364dd60961ed273',
    messagingSenderId: '369737957258',
    projectId: 'kicksafe-7913f',
    authDomain: 'kicksafe-7913f.firebaseapp.com',
    storageBucket: 'kicksafe-7913f.firebasestorage.app',
    measurementId: 'G-N4273KZ693',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBErIfQec7_djgv9WF9krMF7SPCSb601W8',
    appId: '1:369737957258:android:be5106bddc75ff911ed273',
    messagingSenderId: '369737957258',
    projectId: 'kicksafe-7913f',
    storageBucket: 'kicksafe-7913f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBugjZm0rxx8012f5N-93xgNQN2eWvARq4',
    appId: '1:369737957258:ios:935299696078c37b1ed273',
    messagingSenderId: '369737957258',
    projectId: 'kicksafe-7913f',
    storageBucket: 'kicksafe-7913f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBugjZm0rxx8012f5N-93xgNQN2eWvARq4',
    appId: '1:369737957258:ios:935299696078c37b1ed273',
    messagingSenderId: '369737957258',
    projectId: 'kicksafe-7913f',
    storageBucket: 'kicksafe-7913f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNaxUbZetx_kFfWr6atp3fbKFfVIBwNhs',
    appId: '1:369737957258:web:7b2690a4bc39f6171ed273',
    messagingSenderId: '369737957258',
    projectId: 'kicksafe-7913f',
    authDomain: 'kicksafe-7913f.firebaseapp.com',
    storageBucket: 'kicksafe-7913f.firebasestorage.app',
    measurementId: 'G-BK66VZ8DE6',
  );
}
